[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
jni = "0.19.0"
uds = { version = "0.2.6" }
tokio = { version = "1.15.0", features = ["rt", "net", "time", "macros"] }
log = "0.4.14"
android_logger = "0.10.1"
